version : "3.3"
services :
  frontend :
     container_name : "frontend-app"
     build : .
     ports :
         - "3000:3000"
     networks:
         - app-network
     environment:
         - REACT_APP_SERVER_URL=http://54.144.92.48:8080/employees

networks:
  app-network:
    driver: bridge
