version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-go-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres-db
    environment:
      DB_HOST: ip-172-31-24-224
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres-db-admin
      DB_PORT: 5432
      ALLOWED_ORIGINS: http://3.95.213.199:3000/employees

  postgres-db:
    image: postgres
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: postgres-db-admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
